name: dev

on:
  push:
    branches: 
      - '**'        # matches every branch
      - '!master'   # excludes master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build projects
        run: dotnet build
                
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2

      - name: Test projects
        run: |
          dotnet test
